### PR TITLE
Documentation & Settings Update

### PR DESCRIPTION
**Pull request by martinheidegger**
`please dont send us an issue` → `please send us an issue` (P. 9)

Closes issue #40.

Addresses issue #42 in the App and documentation.

### CODE REVIEW

**Comment by dkastl** [comment]
Elena mentioned today something about a typo ... could be this one. She liked it and didn't think we have to fix it. Maybe it's a good idea to collect a few issues for a bug-fix release. It can also help us to test the release workflow ... which at the moment isn't done yet thinking of publishing to Google Play for example.

Will create version milestones.

**Review by dkastl — APPROVED** [review]

**Comment by martinheidegger** [comment]
Note: the eu & ngi-ledger icons will remain placeholders until this branch is merged in master!

**Comment by dkastl** [comment]
Yes, I saw it. But why not use relative path?

**Comment by martinheidegger** [comment]
For some reason GitHub doesn't render relative paths properly, if you find a way to get it running, I am all for it.

**Pull request merged**
