### PR TITLE
Adds build workflow

### PR DESCRIPTION
**Pull request by dkastl**

### CODE REVIEW

**Comment by martinheidegger** [comment]
It only install but doesn't run the tests right? Also there is this weird error message: 

```
npm WARN saveError ENOENT: no such file or directory, open '/home/runner/work/mobile/mobile/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/home/runner/work/mobile/mobile/package.json'
npm WARN mobile No description
npm WARN mobile No repository field.
npm WARN mobile No README data
npm WARN mobile No license field.
```

**Comment by dkastl** [comment]
Yes, it does not test, because you said the tests are broken

**Comment by martinheidegger** [comment]
the `fix/test` branch you want to merge should fix that ;)

**Comment by martinheidegger** [comment]
Screen Shot 2020-01-28 at 01 28 01

**Comment by dkastl** [comment]
I did not add tests at all.
and the warning I just see now.

**Comment by martinheidegger** [comment]
Lets change [this](https://github.com/consento-org/mobile/pull/36/files#diff-898e737ee4e56ba042bda31764bed49eR32) to `npm ci`

**Comment by dkastl** [comment]
Hmmm, with `npm ci` it fails ... let's see

**Comment by martinheidegger** [comment]
`/home/runner/work/mobile/mobile/package.json`  could there be a `mobile` too many?

**Comment by dkastl** [comment]
> `/home/runner/work/mobile/mobile/package.json` could there be a `mobile` too many?

Good observation ... but I don't know where.
I just simplified the workflow file. To exclude some possibilities

**Comment by dkastl** [comment]
Not the reason. Do you have an idea where this double `mobile` could com from?

**Comment by dkastl** [comment]
Now it's gone suddenly.
I don't really understand why

**Comment by martinheidegger** [comment]
It doesn't run any tests ...

**Comment by dkastl** [comment]
Well, all I do is run `npm ci`. Is there some alternative?

**Comment by martinheidegger** [comment]
I think we need to add `npm test` [here](https://github.com/consento-org/mobile/pull/36/files#diff-898e737ee4e56ba042bda31764bed49eR26)

**Comment by dkastl** [comment]
Before or after `npm ci`?

**Comment by martinheidegger** [comment]
After

**Comment by dkastl** [comment]
Seems to test now

```
Test Suites: 4 passed, 4 total
Tests:       35 passed, 35 total
Snapshots:   0 total
Time:        4.854s
Ran all test suites.
```

**Pull request merged**
