### PR TITLE
Prepare v1.0.1 release

### PR DESCRIPTION
**Pull request by dkastl**
- [x] Increases version and build numbers
- [ ] ???

### CODE REVIEW

**Comment by martinheidegger** [comment]
Shouldn't releases go into `master` while `next` kind-of refers to the nightly/beta/current version in the repo?

**Review by martinheidegger — APPROVED** [review]
LGTM

**Comment by dkastl** [comment]
Not sure about the policy. I thought everything should go first to `next` and then to `master`. Otherwise we had to pull changes from `master` into `develop`.

**Comment by martinheidegger** [comment]
🤔 🤷‍♀ I am actually not sure which I like better. The problem if we put it to next → master is that we need two PR's due to the push restrictions in place for the branches.

**Comment by dkastl** [comment]
Let's try once. I just want to build new binaries for the app stores.

**Pull request merged**
