### PR TITLE
Fixing screenshot generator & screenshots &  lint & jest test

### PR DESCRIPTION
**Pull request by martinheidegger**
This PR fixes a bunch of tests. @dkastl Do you think we can integrate this into CI now?

### CODE REVIEW

**Comment by dkastl** [comment]
Probably. 
Does this also fix tests?

**Comment by dkastl** [comment]
Who merges this?

**Comment by martinheidegger** [comment]
It would be nice if you could add a ci workflow to this branch and see if the tests pass on the ci thingy.

**Comment by dkastl** [comment]
The CI thingy does not really test. It just runs publish command. the problem is, I don't know where to publish this. to which channel.

**Comment by dkastl** [comment]
Now I added the GH Actions workflow for all `fix/*` branches:
https://github.com/consento-org/mobile/blob/fix/tests/.github/workflows/expo.yml#L8

But it will not run `expo publish`. It will complete before.
When there are tests though it will also run the tests.

**Comment by martinheidegger** [comment]
Hmm... It should run with every pull request and 

> Secrets are not passed to workflows that are triggered by a pull request from a fork. Learn more. 
[link](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)

The secrets should only be run on master/next branch

**Comment by dkastl** [comment]
OK. With pull request I can do ... maybe I will create a different workflow for that.

**Comment by dkastl** [comment]
Also works

**Pull request merged**
