### PR TITLE
Update issue templates

### PR DESCRIPTION
**Pull request by dkastl**

### CODE REVIEW

**Review by martinheidegger — CHANGES_REQUESTED** [review]
This PR seems to be using an issue template for websites, it doesn't really reflect what sort of issues people run in here. i.e. "Usability Issue", "Broken state", "Development issue"....

**Comment by dkastl** [comment]
This is what Github suggests. I thought to start with the default, then modify it. Github immediately turns this into a pull request and I had no time yet to modiffy it.

Other possibility: start with a blank file, but like this we have already the file in the right folder with standardized naming. Less stuff to think about.

**Comment by dkastl** [comment]
Made the bug report template more simple.

**Review by martinheidegger — APPROVED** [review]

**Comment by martinheidegger** [comment]
Yeah, its a start.

**Pull request merged**
